services:
  - type: web
    name: sangwayixi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        value: sangwa-admin-key
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: APP_BASE_URL
        value: https://www.kunga.me
