services:
  - type: web
    name: sangwayixi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        value: sangwa-admin-key
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
